
export type ClassLevel = '6' | '7' | '8' | '9' | '10' | '11' | '12' | 'COMPETITION';

export type Board = 'CBSE' | 'BSEB' | 'COMPETITION';

export type Stream = 'Science' | 'Commerce' | 'Arts';

export type Role = 'STUDENT' | 'ADMIN' | 'SUB_ADMIN';

export type ContentType = 'NOTES_SIMPLE' | 'NOTES_PREMIUM' | 'MCQ_ANALYSIS' | 'MCQ_SIMPLE' | 'PDF_FREE' | 'PDF_PREMIUM' | 'PDF_ULTRA' | 'PDF_VIEWER' | 'WEEKLY_TEST' | 'VIDEO_LECTURE' | 'NOTES_HTML_FREE' | 'NOTES_HTML_PREMIUM' | 'NOTES_IMAGE_AI';

export interface ExternalApp {
  id: string;
  name: string;
  url: string;
  icon?: string; // Optional icon name or url
  isLocked: boolean;
  creditCost: number;
}

export interface SubjectProgress {
  currentChapterIndex: number; // Starts at 0 (Chapter 1)
  totalMCQsSolved: number; // Must reach 100 to advance index
}

export interface PrizeEntry {
  id: string;
  userId: string;
  userName: string;
  prize: string;
  reason: string;
  date: string;
  scorePercentage: number;
}

export interface InboxMessage {
  id: string;
  text: string;
  date: string;
  read: boolean;
  type?: 'TEXT' | 'REWARD' | 'GIFT'; // Added GIFT
  reward?: {
      tier: 'WEEKLY' | 'MONTHLY' | 'YEARLY' | 'LIFETIME'; // Added YEARLY
      level: 'BASIC' | 'ULTRA';
      durationHours: number;
  };
  gift?: {
      type: 'CREDITS' | 'SUBSCRIPTION' | 'ANIMATION';
      value: number | string; // Coins amount or Sub Tier or Animation ID
      durationHours?: number; // For limited time features
  };
  expiresAt?: string;
  isClaimed?: boolean;
}

export interface User {
  id: string; // Login ID (Firebase UID)
  displayId?: string; // Visible ID (IIC-XXX)
  password: string;
  name: string;
  mobile: string;
  email: string;
  role: Role;
  createdAt: string;
  credits: number; // Premium Credits
  streak: number; // Consecutive days
  lastLoginDate: string; // ISO Date string YYYY-MM-DD
  lastActiveTime?: string; // ISO String for "Online" status
  redeemedCodes: string[]; // List of redeemed code IDs
  
  // Soft Delete / Ban Logic
  isArchived?: boolean; // Acts as Soft Delete / Recycle Bin
  isLocked?: boolean;   // NEW: Hard Lock (Login Denied, but not deleted)
  deletedAt?: string; // ISO Date when deleted. If > 30 days, auto purge.
  recoveryCode?: string; // Generated by Admin to restore account
  isPasswordless?: boolean; // NEW: Allow login without password (Admin Approved Recovery)
  
  // GRANULAR BANS
  isChatBanned?: boolean; // Can't send messages
  isGameBanned?: boolean; // Can't play Spin Wheel
  
  // ROLE & PERMISSIONS
  isSubAdmin?: boolean; // If true, role is effectively ADMIN but with restricted permissions
  permissions?: string[]; // List of allowed feature codes e.g. ['MANAGE_SUBS', 'VIEW_USERS']

  // COMMUNICATION
  inbox?: InboxMessage[]; // Messages from Admin
  
  // REWARDS SYSTEM
  pendingRewards?: PendingReward[];
  isRewardsUnlocked?: boolean; // 10 Coin Gate
  isAutoDeductEnabled?: boolean; // NEW: Skip confirmation popup for credit spending

  // New Fields for Student Profile
  board?: Board;
  classLevel?: ClassLevel;
  stream?: Stream; // Only for 11/12
  
  // Chat & Premium Features
  isPremium?: boolean;
  lastChatTime?: string; // ISO String for cooldown
  lastSpinTime?: string; // ISO String (Legacy)
  dailySpinDate?: string; // YYYY-MM-DD for resetting daily count
  dailySpinCount?: number; // Number of spins used today
  lastRewardClaimDate?: string; // To track daily 3-hour study reward
  lastLoginRewardDate?: string; // NEW: Daily Login Bonus (10 coins)
  
  // SUBSCRIPTION MANAGEMENT
  subscriptionTier?: 'FREE' | 'WEEKLY' | 'MONTHLY' | '3_MONTHLY' | 'YEARLY' | 'LIFETIME' | 'CUSTOM'; // Added 3_MONTHLY and CUSTOM
  subscriptionLevel?: 'BASIC' | 'ULTRA'; // NEW: Granular level for Real subscribers
  subscriptionEndDate?: string; // ISO Date when subscription expires
  subscriptionPrice?: number; // Price admin set for this user's subscription
  grantedByAdmin?: boolean; // True if subscription was granted free by admin
  customSubscriptionName?: string; // For CUSTOM tier
  customSubscriptionDuration?: {
    years: number;
    months: number;
    days: number;
    hours: number;
    minutes: number;
    seconds: number;
  };
  
  // Progress Tracking
  progress: Record<string, SubjectProgress>; // Key is subjectID
  
  // New Analytics Data
  mcqHistory?: MCQResult[]; // List of all completed tests
  topicStrength?: Record<string, { correct: number, total: number }>; // Key: subjectId or topicId
  
  // History & Usage
  subscriptionHistory?: SubscriptionHistoryEntry[];
  usageHistory?: UsageHistoryEntry[];
}

export interface SubscriptionHistoryEntry {
  id: string;
  tier: string; // 'WEEKLY', 'MONTHLY', etc.
  level: string; // 'BASIC', 'ULTRA'
  startDate: string;
  endDate: string;
  durationHours: number;
  price: number; // Amount paid (or 0)
  originalPrice: number; // Value of the plan
  isFree: boolean; // True if reward/admin grant
  grantSource: 'PURCHASE' | 'REWARD' | 'ADMIN' | 'BONUS';
  grantedBy?: string; // ID of the Admin/Sub-Admin who granted this
  grantedByName?: string; // Name of the Admin/Sub-Admin
}

export interface UsageHistoryEntry {
  id: string;
  type: 'VIDEO' | 'PDF' | 'MCQ';
  itemId: string;
  itemTitle: string;
  subject: string;
  durationSeconds: number;
  timestamp: string;
}

export interface CreditPackage {
  id: string;
  name: string;
  credits: number;
  price: number;
  color?: string; // Visual color for the card
}

export interface SubscriptionPlan {
  id: string;
  name: string;
  duration: string; // e.g., "7 days", "30 days"
  
  // Basic Tier (MCQ + Notes)
  basicPrice: number;
  basicOriginalPrice: number;
  
  // Advance/Ultra Tier (PDF + Video)
  ultraPrice: number;
  ultraOriginalPrice: number;
  
  features: string[]; // Generic features list or split logic
  popular?: boolean;
}

export interface RecycleBinItem {
  id: string; // Unique delete ID
  originalId: string; // ID of the actual item
  type: 'USER' | 'CHAPTER' | 'CONTENT' | 'POST' | 'MCQ_BATCH';
  name: string; // For display
  data: any; // Full object to restore
  deletedAt: string;
  expiresAt: string; // 90 days later
  restoreKey?: string; // LocalStorage key to restore to
}

export interface PaymentRequest {
  id: string;
  userId: string;
  userName: string;
  packageId: string;
  packageName: string;
  amount: number;
  txnId: string; // User entered Transaction ID/UTR
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  timestamp: string;
}

// NEW INTERFACE
export interface RecoveryRequest {
  id: string; // User ID
  name: string;
  mobile: string;
  timestamp: string;
  status: 'PENDING' | 'RESOLVED';
}

export interface StartupConfig {
    enabled: boolean;
    duration: number; // Seconds
    title: string;
    features: string[]; // List of text
    bgColor: string;
    textColor: string;
}

export interface SystemSettings {
  appName: string; // Long Name
  appShortName?: string; // e.g. "IIC"
  playerBrandingText?: string; // NEW: Custom Video Player Overlay Text
  playerBlockShare?: boolean; // NEW: Block Share
  watermarkConfig?: WatermarkConfig; // NEW: Global Watermark Config
  appLogo?: string; // NEW: Base64 Logo Image
  syllabusType?: 'SCHOOL' | 'COMPETITIVE' | 'DUAL'; // Updated: DUAL support
  footerText?: string; // NEW: Customized footer text
  showFooter?: boolean; // NEW: Control footer visibility
  footerColor?: string; // NEW: Customized footer color
  aiName?: string;
  themeColor?: string;
  maintenanceMode?: boolean;
  maintenanceMessage?: string;
  customCSS?: string;
  apiKeys?: any[];
  adminCode?: string;
  adminEmail?: string;
  adminPhones?: {id: string, number: string, name: string, isDefault?: boolean}[];
  paymentNumbers?: { id: string, number: string, name: string, dailyClicks: number, lastResetDate: string }[]; // Updated
  defaultAdminPermissions?: string[];
  welcomeTitle?: string;
  welcomeMessage?: string;
  termsText?: string;
  supportEmail?: string;
  aiModel?: string;
  aiInstruction?: string;
  aiPromptNotes?: string;
  aiPromptNotesPremium?: string;
  aiPromptMCQ?: string;
  aiPromptNotesCompetition?: string;
  aiPromptNotesPremiumCompetition?: string;
  aiPromptMCQCompetition?: string;
  marqueeLines?: string[];
  liveMessage1?: string;
  liveMessage2?: string;
  wheelRewards?: any[];
  chatCost?: number;
  dailyReward?: number;
  signupBonus?: number;
  isChatEnabled?: boolean;
  isGameEnabled?: boolean;
  allowSignup?: boolean;
  loginMessage?: string;
  gameCost?: number;
  spinLimitUltra?: number;
  spinLimitBasic?: number;
  spinLimitFree?: number;
  allowedClasses?: string[];
  allowedBoards?: string[];
  allowedStreams?: string[];
  hiddenSubjects?: string[];
  storageCapacity?: string;
  isPaymentEnabled?: boolean;
  upiId?: string;
  upiName?: string;
  qrCodeUrl?: string;
  paymentInstructions?: string;
  packages?: CreditPackage[];
  subscriptionPlans?: SubscriptionPlan[];
  startupAd?: StartupConfig;
  // NEW: 3-Tier Popup Control (Free vs Ultra)
  appFeatures?: AppFeature[];
  profileEditCost?: number;
  nameChangeCost?: number;
  defaultVideoCost?: number;
  engagementRewards?: EngagementReward[];
  weeklyTests?: WeeklyTest[];
  noticeText?: string;
  aiLoadingImage?: string;
  // NEW: Feature Popup Config
  featurePopup?: {
    enabled: boolean;
    intervalMinutes: number; // e.g., 60 for 1 hour
    freeFeatures: string[];
    premiumFeatures: string[];
    showToPremiumUsers: boolean;
    showNearExpiryHours: number; // 24
  };
  threeTierPopupConfig?: {
    enabled: boolean;
    autoCloseSeconds: number;
    skipDelaySeconds: number;
    showToPremium: boolean;
    intervalMinutes?: number;
    showNearExpiryHours?: number;
  };
  dailyChallengeConfig?: {
    mode: 'AUTO' | 'MANUAL';
    rewardPercentage: number;
    selectedChapterIds?: string[];
  };
  themeConfig?: {
    freeTheme: 'BASIC' | 'ULTRA' | 'DARK' | 'LIGHT';
    enableTop3Gold: boolean;
  };
  dashboardLayout?: Record<string, { id: string, visible: boolean, label?: string, order?: number }>; // NEW: Layout Config
  paymentDisabledMessage?: string;
  showTermsPopup?: boolean;
  showWelcomePopup?: boolean;
  welcomePopupTarget?: 'ALL' | 'FREE_ONLY' | 'ULTRA_ONLY';
  specialDiscountEvent?: {
    enabled: boolean;
    eventName: string; // e.g., "Diwali Offer"
    discountPercent: number;
    showToFreeUsers: boolean;
    showToPremiumUsers: boolean;
    renewalDiscountPercent?: number; // Extra discount for already subscribed users
    endsAt?: string; // ISO Date for countdown
    duration?: {
      years: number;
      months: number;
      days: number;
      hours: number;
      minutes: number;
      seconds: number;
    };
  };
}

export interface ContentInfoItem {
  enabled: boolean;
  title: string;
  details: string; // Multiline
  bestFor: string; // Multiline
}

export interface ContentInfoConfig {
  freeNotes: ContentInfoItem;
  premiumNotes: ContentInfoItem;
  freeVideo: ContentInfoItem;
  premiumVideo: ContentInfoItem;
}

export interface ChatRoom {
  id: string;
  name: string;
  type: 'PUBLIC' | 'PRIVATE' | 'ANNOUNCEMENT'; // PUBLIC = Open to all, PRIVATE = Invite only (future), ANNOUNCEMENT = Admin only post
  enabled: boolean;
  icon?: string; // Icon name from Lucide
  description?: string;
}

export interface AppFeature {
  id: string;
  title: string;
  enabled: boolean;
  order: number;
}

export interface SpinReward {
  id: string;
  type: 'COINS' | 'SUBSCRIPTION';
  value: number | string; // Coins amount or Sub Tier (e.g., 'WEEKLY_BASIC')
  label: string;
  probability?: number; // Optional weighting
  color?: string; // Optional custom color
}

export interface FeaturedItem {
  id: string;
  title: string; // "Trigonometry MCQs"
  subtitle?: string; // "Class 10 Math"
  board: Board;
  classLevel: ClassLevel;
  stream: Stream | null;
  subject: Subject; // Store full object for easy reconstruction
  chapter: Chapter; // Store full object
  type: 'MCQ' | 'PDF' | 'VIDEO'; // Simple mapping to tab
}

export interface EngagementReward {
  id: string;
  seconds: number; // e.g., 600 for 10 mins
  type: 'COINS' | 'SUBSCRIPTION';
  amount?: number; // for COINS
  subTier?: 'WEEKLY' | 'MONTHLY' | 'LIFETIME'; // for SUBSCRIPTION
  subLevel?: 'BASIC' | 'ULTRA'; // 'BASIC' or 'ULTRA'
  durationHours?: number; // How long the sub lasts
  label: string; // "10 Mins Study: 2 Coins"
  enabled: boolean;
}

export interface GiftCode {
  id: string;
  code: string;
  type: 'CREDITS' | 'SUBSCRIPTION'; // New: Type of code
  amount?: number; // For Credits
  subTier?: 'WEEKLY' | 'MONTHLY' | '3_MONTHLY' | 'YEARLY' | 'LIFETIME' | 'CUSTOM'; // For Subscription
  subLevel?: 'BASIC' | 'ULTRA'; // For Subscription
  duration?: { // For Custom Subscription
      years: number;
      months: number;
      days: number;
      hours: number;
      minutes: number;
      seconds: number;
  };
  createdAt: string;
  isRedeemed: boolean;
  redeemedBy?: string | string[]; // User ID or List of User IDs
  redeemedDate?: string;
  generatedBy: string; // Admin ID (or name)
  maxUses?: number; // New: Multiple use support
  usedCount?: number; // New: Track usage
}

export interface PendingReward {
  id: string;
  type: 'COINS' | 'SUBSCRIPTION';
  amount?: number; // For Coins
  subTier?: 'WEEKLY' | 'MONTHLY' | 'LIFETIME'; // For Sub
  subLevel?: 'BASIC' | 'ULTRA';
  durationHours?: number;
  expiresAt: string;
  unlockDate?: string; // NEW: When this reward becomes claimable
  label: string;
}

export interface ChatMessage {
  id: string;
  userId: string;
  userName: string;
  userRole: Role;
  text: string;
  timestamp: string;
  isDeleted?: boolean; // Soft delete flag
  deletedAt?: string;  // For 30 day recovery
  replyTo?: {
    id: string;
    userName: string;
    text: string;
  };
}

export interface IICPost {
  id: string;
  type: 'TEXT' | 'IMAGE' | 'VIDEO';
  title?: string;
  content: string; // Text content, Base64 Image string, or Video URL
  timestamp: string;
  authorName: string;
}

export interface Subject {
  id: string;
  name: string;
  icon: string;
  color: string;
}

export interface Chapter {
  id: string;
  title: string;
  description?: string;
}

export interface WatermarkConfig {
  text: string;
  opacity: number; // 0 to 1
  color: string;
  backgroundColor: string;
  fontSize: number;
  isRepeating: boolean;
  positionX: number; // %
  positionY: number; // %
  rotation: number; // deg
}

export interface MCQItem {
  question: string;
  options: string[];
  correctAnswer: number; // Index 0-3
  explanation: string;
  mnemonic?: string; // Memory Trick
  concept?: string; // Full concept explanation
}

// NEW: Performance Analytics
export type PerformanceTag = 'EXCELLENT' | 'GOOD' | 'BAD' | 'VERY_BAD';

export interface MCQResult {
  id: string; // Unique Result ID
  userId: string;
  chapterId: string;
  subjectId: string;
  subjectName: string;
  chapterTitle: string;
  date: string;
  
  totalQuestions: number;
  correctCount: number;
  wrongCount: number;
  score: number;
  
  totalTimeSeconds: number; // Total time spent in session
  averageTimePerQuestion: number;
  performanceTag: PerformanceTag; // Overall Tag
  
  questionTimes?: number[]; // Array of seconds taken per question (optional detail)
  
  // OMR DATA
  classLevel?: string;
  omrData?: {
      qIndex: number;
      selected: number; // -1 if skipped
      correct: number;
  }[];
}

export interface LeaderboardEntry {
    id: string;
    userId: string;
    userName: string;
    score: number;
    total: number;
    date: string;
    topic: string;
}

export interface ActivityLogEntry {
  id: string;
  userId: string;
  userName: string;
  action: string; // 'LOGIN', 'SIGNUP', 'TEST', 'CONTENT', 'ADMIN'
  details: string;
  timestamp: string;
  role: Role;
}

export interface HtmlModule {
  id: string;
  title: string;
  url: string;
  price: number;
  access: 'FREE' | 'BASIC' | 'ULTRA';
}

export interface PremiumNoteSlot {
  id: string;
  title: string;
  url: string;
  color: string; // Hex or Class
  access: 'BASIC' | 'ULTRA'; 
}

export interface LessonContent {
  id: string; // unique ID for history
  title: string;
  subtitle: string;
  content: string; // URL for PDF/Link Mode
  type: ContentType;
  dateCreated: string;
  subjectName: string;
  mcqData?: MCQItem[]; // Structure for MCQ mode
  
  // DUAL SYLLABUS CONTENT
  schoolVideoPlaylist?: {title: string, url: string, price?: number, access?: 'FREE' | 'BASIC' | 'ULTRA'}[];
  competitionVideoPlaylist?: {title: string, url: string, price?: number, access?: 'FREE' | 'BASIC' | 'ULTRA'}[];
  schoolPdfLink?: string;
  schoolPdfPrice?: number;
  competitionPdfLink?: string;
  competitionPdfPrice?: number;
  
  schoolPdfPremiumSlots?: PremiumNoteSlot[];
  competitionPdfPremiumSlots?: PremiumNoteSlot[];

  videoPlaylist?: {title: string, url: string, price?: number, access?: 'FREE' | 'BASIC' | 'ULTRA'}[]; // LEGACY
  
  // CUSTOM SLOTS (6/6/6)
  customPdf?: { id: string, name: string, link: string, price: number }[];
  customVideo?: { id: string, name: string, link: string, price: number }[];
  customMcq?: { id: string, name: string, data: MCQItem[], price: number }[];
  
  // HTML INTERACTIVE MODULES (10 Slots)
  htmlModules?: HtmlModule[];

  // PREMIUM NOTE SLOTS (20 Slots)
  premiumNoteSlots?: PremiumNoteSlot[];

  videoPrice?: number; // Global or default video price
  ultraPdfLink?: string; // Ultra PDF
  ultraPdfPrice?: number; // Ultra PDF Price
  aiImageLink?: string; // NEW: AI Generated Image Notes
  aiHtmlContent?: string; // NEW: HTML Content for AI Notes
  aiImagePrice?: number; // Price for AI Image Notes
  isComingSoon?: boolean; // If content is missing
  userAnswers?: Record<number, number>; // Saved answers for History/Analysis
}

export type ViewState = 'BOARDS' | 'CLASSES' | 'STREAMS' | 'SUBJECTS' | 'CHAPTERS' | 'LESSON' | 'ADMIN_DASHBOARD' | 'AUDIO_STUDIO' | 'STUDENT_DASHBOARD' | 'UNIVERSAL_CHAT' | 'RULES' | 'IIC' | 'LEADERBOARD';

export interface WeeklyTest {
  id: string;
  name: string;
  description: string;
  isActive: boolean;
  classLevel: ClassLevel;
  questions: MCQItem[];
  totalQuestions: number;
  passingScore: number;
  createdAt: string;
  durationMinutes?: number; // Default 120 (2 hours)
  autoSubmitEnabled?: boolean; // Auto-submit after timeout
  selectedSubjects?: string[]; // Subject IDs included in this test
  selectedChapters?: string[]; // Chapter IDs included in this test (mix from multiple)
}

// 2.0 FEATURES
export interface Challenge20 {
    id: string; // "challenge-{timestamp}"
    title: string;
    description?: string;
    questions: MCQItem[];
    createdAt: string; // ISO
    expiryDate: string; // ISO (createdAt + 24h)
    type: 'DAILY_CHALLENGE' | 'WEEKLY_TEST';
    classLevel: ClassLevel;
    isAutoGenerated: boolean; // True if "Auto Mix" used
    isActive: boolean;
    durationMinutes?: number; // NEW: Admin customized timer
}

export interface QuestionBankItem {
    id: string; // Unique ID
    question: MCQItem;
    subject: string;
    topic?: string;
    classLevel: ClassLevel;
    difficulty?: 'EASY' | 'MEDIUM' | 'HARD';
    createdAt: string;
    source: 'AI' | 'MANUAL';
}

export interface StudentTestAttempt {
  testId: string;
  userId: string;
  startedAt: string; // ISO timestamp
  submittedAt?: string;
  score?: number;
  answers: Record<number, number>; // question index -> selected answer index
}

export type StudentTab = 'HOME' | 'COURSES' | 'ROUTINE' | 'HISTORY' | 'REDEEM' | 'PREMIUM' | 'GAME' | 'WEEKLY_TEST' | 'PROFILE' | 'LEADERBOARD' | 'STORE' | 'VIDEO' | 'PDF' | 'MCQ' | 'ANALYTICS' | 'PRIZES' | 'REWARDS' | 'UPDATES' | 'SUB_HISTORY';

export type Language = 'English' | 'Hindi';

export interface AppState {
  user: User | null;
  originalAdmin: User | null; // NEW: Track Admin when viewing as user
  view: ViewState;
  selectedBoard: Board | null;
  selectedClass: ClassLevel | null;
  selectedStream: Stream | null;
  selectedSubject: Subject | null;
  selectedChapter: Chapter | null;
  chapters: Chapter[];
  lessonContent: LessonContent | null;
  loading: boolean;
  error: string | null;
  language: Language;
  showWelcome: boolean; // Control welcome popup
  globalMessage: string | null; // Admin Broadcast
  settings: SystemSettings; // New Global Settings
}
